### ISSUE TITLE
Broken presents for Jack

### ISSUE THREAD

**Issue by sarahghp** [sarahghp/metaphorgy#2]
Omg I actually did work on Metaphorgy! I need to do some responsiveness stuff, but it is in place for you to mess around with now ...

Except you have to solve this jQuery bug that won't make the #answer div show because I am definitely missing something. It refuses to fadeToggle.

And I am in the middle of learning how to parallax the white container over the headers, which is why it is weirdly long. But hey! progress!

Broken presents for you, Jack.

**Comment by ajacksified** [comment]
Progress! WIll check it out today.
