### ISSUE TITLE
HAPPY BIRTHDAY METAPHORGY!!!

### ISSUE THREAD

**Issue by sarahghp** [sarahghp/metaphorgy#34]
PARTY WOO YEA

![image](https://cloud.githubusercontent.com/assets/1477362/5097153/2d2664c0-6f46-11e4-907e-2f74142e918e.png)

**Comment by ajacksified** [comment]
![fireworks](http://media.giphy.com/media/UbToNUhGJH2Lu/giphy.gif)

**Comment by sarahghp** [comment]
http://giphy.com/gifs/crying-2WxWfiavndgcM

**Comment by ajacksified** [comment]
8 MONTHS TO NEXT BIRTHDAY :cake: :balloon:
